window.JAM_MODEL = {
  phases:[
    {weeks:"1–2",name:"Refine & prepare",outcome:"Pods and PMs agree on what they will do and how they expect to deliver.",meetings:["Self-organized pod refinement and planning","Midway leadership sync within each function","Delivery pitchbacks with PMs","Full-group delivery kickoff"],inspect:"A credible pod plan and shared understanding at pitchback. PM availability is protected for refinement.",events:["pitchback"]},
    {weeks:"3–4",name:"Explore & shape",outcome:"Current solutions take shape; next-cycle possibilities are visible before we choose the portfolio.",meetings:["PMs share their candidate thinking","Design Demo Day","Input from across the business by week-four end"],inspect:"Candidate problems, their evidence, and possible collaborators are clear enough to compare. Current delivery has concrete early work to show.",events:["candidates","designdemo"]},
    {weeks:"5–6",name:"Choose & mature",outcome:"The business invests in the next portfolio; the current design is buttoned up and the increment is ready to finish.",meetings:["Product alignment on the investment proposal","Portfolio Review at the end of week six","Delivery check-ins before enablement"],inspect:"The portfolio is investment-ready. Design has completed most of what the pod needs. Product can explain the actual current increment.",events:["portfolio","designfinish","deliverycheck"]},
    {weeks:"7–8",name:"Finish & look ahead",outcome:"The current increment reaches Demo Day; frontline teams are prepared and next-cycle work has enough context to begin refinement.",meetings:["Enablement at the start of each of the last two weeks","Light, self-organized next-opportunity intake","Demo Day at cycle end"],inspect:"A viable delivered increment, real release state, prepared frontline teams, and lightly shaped next opportunities.",events:["enablement","intake","demoday"]}
  ],
  teams:{
    product:{name:"Product",role:"Choose what deserves investment. Prepare the pods, prepare the work, and prepare the business.",peak:"Portfolio Review · end of week 6",recovery:1,recoveryHeading:"Learn and choose the next work",after:"The release and refinement push spans the cycle boundary, from weeks 7–8 into weeks 1–2.",balance:"Cool down, reflection, and learning alongside the next opportunity set.",pressure:"An overloaded candidate deadline can turn this window into another crunch.",work:[
      {title:"Refine with pods",support:"Finish previous releases",cycle:"Current + previous",detail:"Be available to help pods understand and refine the selected investments, while closing out prior release and frontline enablement work.",items:["Protect open time for pod conversations.","Help teams arrive at a shared delivery approach.","Finish previous-cycle release work."],result:"Aligned pod plans and completed prior-release work."},
      {title:"Shape the next opportunities",support:"Learn, cool down, ramp up",cycle:"Next cycle",detail:"Move from loose ideas and priorities to a visible candidate set. Learn from recent work, customer and business evidence, the world around us, and available capacity.",items:["Use the first week and a half for thinking and learning.","Share the shape of the candidate set by week-four end.","Include proposals from Design, Engineering, and the wider business."],result:"Problem, evidence, and possible collaborators for each candidate."},
      {title:"Choose the next portfolio",support:"Prepare the business review",cycle:"Next cycle",detail:"Compare candidates, trade priorities against capacity, and add enough detail for the business to choose where to invest.",items:["Make the proposed investments and trade-offs clear.","Keep the problem and evidence stronger than a prescribed solution.","Review the portfolio with the business at week-six end."],result:"A selected investment set for the next cycle."},
      {title:"Enable & prepare intake",support:"Get current work out the door",cycle:"Current + next",detail:"Help frontline teams prepare for current releases, while offering partial availability for leaders to explore the next opportunities.",items:["Enable at the beginning of weeks seven and eight.","Reuse the product and delivery understanding already shared.","Keep next-cycle documentation and collaboration light."],result:"Prepared frontline teams and next opportunities ready for refinement."}
    ]},
    design:{name:"Design",role:"Turn opportunity into a clear solution, then support the pod as that solution takes shape and reaches the finish.",peak:"Pencils down · end of week 6",recovery:3,recoveryHeading:"Support the finish and turn toward the next work",after:"Weeks 5–6 complete the design work progressively, leaving the pod buttoned up before its final delivery push.",balance:"Cool down alongside spot checks, QA support, and light next-opportunity thinking.",pressure:"Substantial late design work can crowd out cooldown and leave Engineering too much to finish.",work:[
      {title:"Refine the solution",support:"Iterate with PMs & engineers",cycle:"Current cycle",detail:"Put forward meaningful solution increments that demonstrate clear thinking. The planning-end V1 is a revisable expression of the solution, with an investment we can afford to throw away.",items:["Work directly with the pod and PM during refinement.","Use successive versions to build shared understanding.","Keep early solution work open to change."],result:"A meaningful solution increment for the pod to build from."},
      {title:"Iterate alongside delivery",support:"Show the emerging experience",cycle:"Current cycle",detail:"Stay close as implementation teaches us what needs to change. Design Demo Day lets the whole organization see where the work is headed.",items:["Test and refine the experience with the pod.","Carry learning back into the solution.","Show the design direction at Design Demo Day."],result:"A clearer solution informed by implementation."},
      {title:"Finish & button up design",support:"Enable the pod to finish",cycle:"Current cycle",detail:"Complete design finishing touches progressively. By the end of week six, most of what the pod needs is done, so substantial design work does not arrive too late in delivery.",items:["Settle the intended experience and remaining design context.","Keep supporting Engineering as the work matures.","Reach pencils down at week-six end."],result:"Engineering has what it needs for the final two-week push."},
      {title:"Spot check & think ahead",support:"Cool down while supporting the pod",cycle:"Current + next",detail:"Support the current finish through spot checks and QA, while making room for cooldown and light early thinking on the next opportunities.",items:["Stay available for the pod's remaining needs.","Participate in next-opportunity conversations as a leader.","Explore disposable early solution ideas."],result:"Current experience checked; next solution thinking begun lightly."}
    ]},
    engineering:{name:"Engineering",role:"Turn the selected opportunity into a viable product increment. Pods organize how they plan, build, and finish.",peak:"Demo Day & delivery · end of week 8",recovery:0,recoveryHeading:"Cool down while planning the next delivery",after:"The previous increment has just crossed the delivery finish line.",balance:"Cool down alongside self-organized planning, refinement, and ramp-up.",pressure:"Carryover and preparation can fill the whole window unless space for cooldown is protected.",work:[
      {title:"Plan & ramp up",support:"Cool down after the last delivery",cycle:"Current cycle",detail:"Balance cooldown after the previous cycle with the planning and refinement needed to be ready for six weeks of delivery.",items:["Self-organize the pod's planning and cooldown.","Coordinate across pods through engineering leaders.","Pitch back the work and delivery approach with the PM."],result:"A shared plan and readiness to begin focused delivery."},
      {title:"Explore & prototype",support:"Uncover the big pieces",cycle:"Current cycle",detail:"Learn, uncover unknowns, build prototypes, and flesh out the large pieces of implementation while Design continues to iterate.",items:["Make the work concrete enough to learn from.","Explore the technical shape and important unknowns.","Show a demonstrable prototype where useful."],result:"Early working evidence and a clearer implementation path."},
      {title:"Mature the increment",support:"Round out implementation",cycle:"Current cycle",detail:"Develop a tangible, fairly well-understood increment. Product should be able to describe it before the final business enablement push.",items:["Mature the broad pieces into working behavior.","Resolve design questions progressively with Design.","Make delivery truth clear in the delivery check-in."],result:"A known, describable increment with finishing work remaining."},
      {title:"Finish & deliver",support:"Look at next work lightly",cycle:"Current + next",detail:"Complete the final delivery work and demonstrate the increment at Demo Day. Keep next-cycle intake light while finishing the current investment.",items:["Round out and verify the current increment.","Work with Design on remaining spot checks and quality.","Surface the real release state at Demo Day."],result:"A viable delivered increment and readiness for the next planning phase."}
    ]}
  },
  milestones:[
    {id:"pitchback",title:"Pitchbacks & kickoff",when:"End W2 / start W3",short:"W2",cycle:"Current cycle",phase:0,purpose:"The pod and PM agree on what will be delivered and how; the full group sees the plans.",people:"Pods and PMs for pitchbacks; the full group for kickoff.",evidence:["Intended work and delivery approach","Shared understanding of the opportunity and solution"],outcomes:["Alignment before delivery begins","A visible plan for the next six weeks"],note:"Pitchbacks are self-organized. Functional leadership syncs midway through planning help surface cross-pod dependencies."},
    {id:"candidates",title:"Next-work candidates",when:"End of week 4",short:"W4",cycle:"Next cycle",phase:1,purpose:"Make the desired body of work visible before choosing what to invest in.",people:"Product, with proposals from Design, Engineering, and anywhere in the business.",evidence:["Business problem","Basis, evidence, and data","Possible collaborators"],outcomes:["A shared candidate set","Room to compare priorities and capacity"],note:"The week-four cutoff is part of this proposed rhythm. Sharing format remains open; it need not mean a new meeting."},
    {id:"designdemo",title:"Design Demo Day",when:"Weeks 3–4 culmination",short:"W4",cycle:"Current cycle",phase:1,purpose:"Show the broader organization where the current experience is headed.",people:"Design presents emerging work to the whole organization.",evidence:["Iterative design work","Engineering prototype, where useful"],outcomes:["Concrete shared understanding of direction","Early visibility into the experience"],note:"The detailed day within this phase is not fixed here. Design and Engineering keep iterating after the share-out."},
    {id:"portfolio",title:"Portfolio Review",when:"End of week 6",short:"W6",cycle:"Next cycle",phase:2,purpose:"The business decides whether these are the right next investments.",people:"Product and the business reviewing investment choices.",evidence:["Proposed portfolio","Problems, evidence, and investment rationale","Scope and trade-offs against capacity"],outcomes:["Selected next investments","Shared context for next-opportunity intake"],note:"Keep enough detail to support the investment decision while leaving delivery teams space to think through the solution."},
    {id:"designfinish",title:"Design pencils down",when:"End of week 6",short:"W6",cycle:"Current cycle",phase:2,purpose:"Button up design so Engineering is not left with substantial design work too late in the cycle.",people:"Designers and their delivery pods.",evidence:["Settled experience","Completed design finishing touches","The remaining context Engineering needs"],outcomes:["Pod enabled for the final delivery push","Design can switch gears with lighter support"],note:"This culminates continuous work with the pod. Spot checks and support continue in weeks seven and eight; a separate handoff meeting is not required by this model."},
    {id:"deliverycheck",title:"Delivery check-ins",when:"Weeks 5–6 culmination",short:"W5–6",cycle:"Current cycle",phase:2,purpose:"Connect actual delivery state to Product's ability to explain the work and enable the business.",people:"The delivery pod and Product.",evidence:["Tangible, fairly known increment","What remains and what is changing","Current release state and meaningful risks"],outcomes:["Product ready to prepare the business","Known gaps and the next relevant decisions"],note:"The detailed day remains open. Build on prior shared work rather than recreate materials for the check-in."},
    {id:"enablement",title:"Frontline enablement",when:"Beginning of weeks 7 & 8",short:"W7–8",cycle:"Current cycle",phase:3,purpose:"Prepare frontline teams to explain and support the upcoming releases.",people:"Product and frontline teams, alongside the relevant downstream owners.",evidence:["Known product and delivery context","Shared material from earlier touchpoints","Remaining release details as they stabilize"],outcomes:["Frontline readiness for current releases","Clear remaining questions and release details"],note:"The existing map identifies Product Marketing and other downstream owners. Their full rhythms are not redesigned in this draft."},
    {id:"intake",title:"Next-opportunity intake",when:"Light touch through weeks 7 & 8",short:"W7–8",cycle:"Next cycle",phase:3,purpose:"Give leaders and pods enough context to begin next-cycle refinement.",people:"Product, Engineering leaders, and designers; every designer is a leader.",evidence:["Selected opportunities","Product's current thinking","Disposable early solution ideas"],outcomes:["Shared problem context","Early solution thinking with room to change"],note:"Self-organized and light while everyone finishes current work. Avoid overdeveloping an answer that biases the pod's thinking."},
    {id:"demoday",title:"Demo Day & delivery",when:"End of week 8",short:"W8",cycle:"Current cycle",phase:3,purpose:"Demonstrate the viable increment and its actual value and release state.",people:"The delivery pods and the full group.",evidence:["Working increment","Intended value","Actual customer exposure and remaining release work"],outcomes:["Delivered and demonstrated work","A clear view of what is ready and available"],note:"Demo Day is the intended release point. Technical delivery, customer release, and business launch can differ; those exceptions must be explicit."}
  ],
  artifacts:[
    {when:"By end of W4",name:"Candidate opportunity",detail:"Problem, evidence, and possible collaborators. Enough shape to compare; still open to change."},
    {when:"End of W6",name:"Portfolio proposal",detail:"Chosen investment set, rationale, and trade-offs against capacity."},
    {when:"Pre-work through W6",name:"Iterative design work",detail:"Disposable early versions, meaningful refinement increments, then settled experience and context."},
    {when:"End of W2",name:"Pod plan & pitchback",detail:"Intended work and how the pod expects to deliver it."},
    {when:"W3–6",name:"Working increment",detail:"Early prototype, then mature delivery truth Product can explain."},
    {when:"W7–8 and release",name:"Enablement material",detail:"Build on shared understanding; close remaining release details as they stabilize."}
  ],
  questions:[
    {name:"Protect real availability",text:"Which standing demands can give way so PMs can meet with pods during refinement and each function has room to cool down?"},
    {name:"Handle late discoveries",text:"How should the pod handle significant design changes after week-six pencils down without overwhelming the final delivery push?"},
    {name:"Match support to the work",text:"What evidence should leaders inspect, and what coaching do newer PMs need to reinforce the process?"},
    {name:"Make investment decisions clear",text:"Who settles competing priorities or capacity conflicts, and what is committed before refinement reveals the solution?"},
    {name:"Keep the wider lifecycle visible",text:"How do QA, acceptance, Product Marketing, release, and launch responsibilities fit around this three-function view?"},
    {name:"Work through exceptions",text:"How do carryover, urgent work, cross-pod dependencies, multiple product lines, and shared people affect this rhythm?"},
    {name:"Give Product useful learning",text:"Who provides the customer access, usage evidence, and frontline feedback needed to choose what matters next?"},
    {name:"Define ongoing operating support",text:"What should Ryan stay close to, what should Chris and Kai retain, and what can the teams manage independently?"},
    {name:"Define early maturity",text:"What should each early solution increment demonstrate, and how much disposable investment is appropriate?"}
  ]
};
